var BookInstance = require('../models/bookinstance')

exports.bookinstance_list = (req, res) => res.send('NOT IMPLEMENTED: BookInstance list')
exports.bookinstance_detail = (req, res) => res.send(`NOT IMPLEMENTED: BookInstance detail: ${req.params.id}`)
exports.bookinstance_create_get = (req, res) => res.send('NOT IMPLEMENTED: BookInstance create get')
exports.bookinstance_create_post = (req, res) => res.send('NOT IMPLEMENTED: BookInstance create post')
exports.bookinstance_delete_get = (req, res) => res.send('NOT IMPLEMENTED: BookInstance delete get')
exports.bookinstance_delete_post = (req, res) => res.send('NOT IMPLEMENTED: BookInstance delete post')
exports.bookinstance_update_get = (req, res) => res.send('NOT IMPLEMENTED: BookInstance update get')
exports.bookinstance_update_post = (req, res) => res.send('NOT IMPLEMENTED: BookInstance update post')
