var Genre = require('../models/genre')

exports.genre_list = (req, res) => res.send('NOT IMPLEMENTED: Genre list')
exports.genre_detail = (req, res) => res.send(`NOT IMPLEMENTED: Genre detail: ${req.params.id}`)
exports.genre_create_get = (req, res) => res.send('NOT IMPLEMENTED: Genre create get')
exports.genre_create_post = (req, res) => res.send('NOT IMPLEMENTED: Genre create post')
exports.genre_delete_get = (req, res) => res.send('NOT IMPLEMENTED: Genre delete get')
exports.genre_delete_post = (req, res) => res.send('NOT IMPLEMENTED: Genre delete post')
exports.genre_update_get = (req, res) => res.send('NOT IMPLEMENTED: Genre update get')
exports.genre_update_post = (req, res) => res.send('NOT IMPLEMENTED: Genre update post')
